name:  sample_pubspec
description:  A sample application

dependencies:
  browser: any
  js: any
  web_ui: any
  dart_rtc_common:
    git: git://github.com/samiy-xx/dart_rtc_common.git
  dart_rtc_client:
    git: git://github.com/samiy-xx/dart_rtc_client.git
